// Preset Looks for AEReality Flutter - 2026 Cinema Presets
// Ported from WebGL app with Vulkan parameter mapping
// Inspired by elite anime editors (adevob, conquestor_, Magic Bullet Looks)

import 'package:flutter/material.dart';

class PresetParams {
  final double brightness;
  final double saturation;
  final double contrast;
  final double sharpness;
  final double gamma;
  final double hue;
  final double temperature; // Kelvin (2000-12000)
  final double glowIntensity;
  final double bloomSpread;
  final bool deepGlow;
  final double deepGlowRadius;
  final double edgeGlow;
  final double edgeGlowSpread;
  final String edgeGlowTint; // 'gold', 'electric', 'cyan', 'warm', 'white', 'crimson'
  final double anamorphicFlare;
  final double flareAmount;
  final double godRays;
  final double godRaysDensity;
  final String godRaysColor; // 'golden', 'cyan', 'violet', 'white', 'crimson'
  final double volumetricLighting;
  final double depthOfField;
  final double? dofFocus;
  final double? dofDirection;
  final double lumenRtx;
  final double volumetricFog;
  final double blackCrush;
  final double lookMix;
  final double vignette;
  final double splitToning;
  final double lutIntensity;
  final double darkOutlines;
  final double denoise;
  final double edgeBlur;
  final double grain;
  final String aspectRatio; // '4:5', '9:16', '16:9', '1:1'

  const PresetParams({
    required this.brightness,
    required this.saturation,
    required this.contrast,
    required this.sharpness,
    required this.gamma,
    required this.hue,
    required this.temperature,
    required this.glowIntensity,
    required this.bloomSpread,
    required this.deepGlow,
    required this.deepGlowRadius,
    required this.edgeGlow,
    required this.edgeGlowSpread,
    required this.edgeGlowTint,
    required this.anamorphicFlare,
    required this.flareAmount,
    required this.godRays,
    required this.godRaysDensity,
    required this.godRaysColor,
    required this.volumetricLighting,
    required this.depthOfField,
    this.dofFocus,
    this.dofDirection,
    required this.lumenRtx,
    required this.volumetricFog,
    required this.blackCrush,
    required this.lookMix,
    required this.vignette,
    required this.splitToning,
    required this.lutIntensity,
    required this.darkOutlines,
    required this.denoise,
    required this.edgeBlur,
    required this.grain,
    required this.aspectRatio,
  });

  // Convert to Map for native bridge
  Map<String, dynamic> toMap() => {
    'brightness': brightness,
    'saturation': saturation,
    'contrast': contrast,
    'sharpness': sharpness,
    'gamma': gamma,
    'hue': hue,
    'temperature': temperature,
    'glowIntensity': glowIntensity,
    'bloomSpread': bloomSpread,
    'deepGlow': deepGlow,
    'deepGlowRadius': deepGlowRadius,
    'edgeGlow': edgeGlow,
    'edgeGlowSpread': edgeGlowSpread,
    'edgeGlowTint': edgeGlowTint,
    'anamorphicFlare': anamorphicFlare,
    'flareAmount': flareAmount,
    'godRays': godRays,
    'godRaysDensity': godRaysDensity,
    'godRaysColor': godRaysColor,
    'volumetricLighting': volumetricLighting,
    'depthOfField': depthOfField,
    'dofFocus': dofFocus ?? 0.5,
    'dofDirection': dofDirection ?? 0.0,
    'lumenRtx': lumenRtx,
    'volumetricFog': volumetricFog,
    'blackCrush': blackCrush,
    'lookMix': lookMix,
    'vignette': vignette,
    'splitToning': splitToning,
    'lutIntensity': lutIntensity,
    'darkOutlines': darkOutlines,
    'denoise': denoise,
    'edgeBlur': edgeBlur,
    'grain': grain,
    'aspectRatio': aspectRatio,
  };
}

class PresetLook {
  final String name;
  final String tagline;
  final String category; // 'Stylized', 'Cinematic', 'Vintage'
  final PresetParams params;

  const PresetLook({
    required this.name,
    required this.tagline,
    required this.category,
    required this.params,
  });
}

final List<PresetLook> PRESET_LOOKS = [
  PresetLook(
    name: 'Adevob: Junho Jr',
    tagline: 'Deep inky black crush, golden warm specular glow, punchy saturation, high-voltage sharpness & warm amber tone',
    category: 'Stylized',
    params: PresetParams(
      brightness: 0.05,
      saturation: 1.35,
      contrast: 1.45,
      sharpness: 0.85,
      gamma: 0.94,
      hue: 0.0,
      temperature: 6600.0,
      glowIntensity: 0.24,
      bloomSpread: 0.38,
      deepGlow: true,
      deepGlowRadius: 0.40,
      edgeGlow: 0.15,
      edgeGlowSpread: 0.32,
      edgeGlowTint: 'gold',
      anamorphicFlare: 0.04,
      flareAmount: 0.25,
      godRays: 0.08,
      godRaysDensity: 0.40,
      godRaysColor: 'golden',
      volumetricLighting: 0.12,
      depthOfField: 0.0,
      lumenRtx: 0.18,
      volumetricFog: 0.04,
      blackCrush: 0.28,
      lookMix: 0.08,
      vignette: 0.16,
      splitToning: 0.02,
      lutIntensity: 0.35,
      darkOutlines: 0.18,
      denoise: 0.0,
      edgeBlur: 0.04,
      grain: 0.012,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Dantaes CC',
    tagline: 'Electric high-voltage contrast, razor anime lines, luminous specular glow, saturated vibrant pop & cool aura energy',
    category: 'Stylized',
    params: PresetParams(
      brightness: 0.04,
      saturation: 1.42,
      contrast: 1.48,
      sharpness: 0.90,
      gamma: 0.92,
      hue: 0.0,
      temperature: 6300.0,
      glowIntensity: 0.28,
      bloomSpread: 0.42,
      deepGlow: true,
      deepGlowRadius: 0.48,
      edgeGlow: 0.20,
      edgeGlowSpread: 0.38,
      edgeGlowTint: 'electric',
      anamorphicFlare: 0.06,
      flareAmount: 0.30,
      godRays: 0.12,
      godRaysDensity: 0.50,
      godRaysColor: 'cyan',
      volumetricLighting: 0.08,
      depthOfField: 0.0,
      lumenRtx: 0.22,
      volumetricFog: 0.05,
      blackCrush: 0.30,
      lookMix: 0.10,
      vignette: 0.15,
      splitToning: 0.04,
      lutIntensity: 0.40,
      darkOutlines: 0.22,
      denoise: 0.0,
      edgeBlur: 0.05,
      grain: 0.012,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Adevob: Saber vs Rin',
    tagline: 'Excalibur golden radiance, Rin Tohsaka crimson jewel energy, inky dark outlines & high-voltage combat clarity',
    category: 'Stylized',
    params: PresetParams(
      brightness: 0.04,
      saturation: 1.30,
      contrast: 1.38,
      sharpness: 0.75,
      gamma: 0.94,
      hue: 0.0,
      temperature: 6400.0,
      glowIntensity: 0.22,
      bloomSpread: 0.42,
      deepGlow: true,
      deepGlowRadius: 0.45,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.36,
      edgeGlowTint: 'gold',
      anamorphicFlare: 0.03,
      flareAmount: 0.20,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'golden',
      volumetricLighting: 0.0,
      depthOfField: 0.0,
      lumenRtx: 0.20,
      volumetricFog: 0.05,
      blackCrush: 0.24,
      lookMix: 0.04,
      vignette: 0.12,
      splitToning: 0.04,
      lutIntensity: 0.35,
      darkOutlines: 0.14,
      denoise: 0.0,
      edgeBlur: 0.06,
      grain: 0.015,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Junho CC',
    tagline: 'K-Drama & Manhwa Cinematic: Velvet crushed shadows, honey warm skin tones, rich specular pop, balanced film contrast',
    category: 'Cinematic',
    params: PresetParams(
      brightness: 0.03,
      saturation: 1.15,
      contrast: 1.30,
      sharpness: 0.60,
      gamma: 0.96,
      hue: 0.0,
      temperature: 6100.0,
      glowIntensity: 0.14,
      bloomSpread: 0.35,
      deepGlow: false,
      deepGlowRadius: 0.30,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.28,
      edgeGlowTint: 'warm',
      anamorphicFlare: 0.0,
      flareAmount: 0.0,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'golden',
      volumetricLighting: 0.0,
      depthOfField: 0.0,
      lumenRtx: 0.12,
      volumetricFog: 0.04,
      blackCrush: 0.20,
      lookMix: 0.06,
      vignette: 0.14,
      splitToning: 0.0,
      lutIntensity: 0.30,
      darkOutlines: 0.08,
      denoise: 0.0,
      edgeBlur: 0.04,
      grain: 0.015,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Adevob: Ichigo vs Uryu',
    tagline: 'Quincy electric blue-white arrows, inky black crush, razor anime lineart & spiritual pressure bloom',
    category: 'Stylized',
    params: PresetParams(
      brightness: 0.04,
      saturation: 1.25,
      contrast: 1.40,
      sharpness: 0.70,
      gamma: 0.92,
      hue: 0.0,
      temperature: 6800.0,
      glowIntensity: 0.26,
      bloomSpread: 0.46,
      deepGlow: true,
      deepGlowRadius: 0.48,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.38,
      edgeGlowTint: 'electric',
      anamorphicFlare: 0.04,
      flareAmount: 0.24,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'cyan',
      volumetricLighting: 0.0,
      depthOfField: 0.0,
      lumenRtx: 0.22,
      volumetricFog: 0.08,
      blackCrush: 0.30,
      lookMix: 0.08,
      vignette: 0.14,
      splitToning: 0.10,
      lutIntensity: 0.40,
      darkOutlines: 0.16,
      denoise: 0.0,
      edgeBlur: 0.06,
      grain: 0.015,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Fern vs Gojo',
    tagline: 'Ethereal Anime Clash: Limitless infinity cyan aura, celestial magic bloom, crystal clear combat clarity & crisp dark ink outlines',
    category: 'Stylized',
    params: PresetParams(
      brightness: 0.05,
      saturation: 1.25,
      contrast: 1.36,
      sharpness: 0.65,
      gamma: 0.94,
      hue: 0.0,
      temperature: 6700.0,
      glowIntensity: 0.26,
      bloomSpread: 0.48,
      deepGlow: true,
      deepGlowRadius: 0.48,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.35,
      edgeGlowTint: 'cyan',
      anamorphicFlare: 0.04,
      flareAmount: 0.22,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'cyan',
      volumetricLighting: 0.06,
      depthOfField: 0.0,
      lumenRtx: 0.20,
      volumetricFog: 0.08,
      blackCrush: 0.24,
      lookMix: 0.06,
      vignette: 0.12,
      splitToning: 0.08,
      lutIntensity: 0.36,
      darkOutlines: 0.14,
      denoise: 0.0,
      edgeBlur: 0.05,
      grain: 0.015,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Sildurs Vibrant Extreme',
    tagline: 'Minecraft Sildurs Shaders: Golden sunset god rays, pink-violet atmospheric scattering, vibrant emerald bounce & crystal water reflections',
    category: 'Stylized',
    params: PresetParams(
      brightness: 0.05,
      saturation: 1.30,
      contrast: 1.28,
      sharpness: 0.55,
      gamma: 0.95,
      hue: 0.0,
      temperature: 5700.0,
      glowIntensity: 0.26,
      bloomSpread: 0.50,
      deepGlow: true,
      deepGlowRadius: 0.50,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.32,
      edgeGlowTint: 'warm',
      anamorphicFlare: 0.03,
      flareAmount: 0.16,
      godRays: 0.40,
      godRaysDensity: 0.55,
      godRaysColor: 'golden',
      volumetricLighting: 0.35,
      depthOfField: 0.0,
      dofFocus: 0.5,
      dofDirection: 0.0,
      lumenRtx: 0.22,
      volumetricFog: 0.14,
      blackCrush: 0.14,
      lookMix: 0.08,
      vignette: 0.10,
      splitToning: 0.0,
      lutIntensity: 0.32,
      darkOutlines: 0.06,
      denoise: 0.0,
      edgeBlur: 0.04,
      grain: 0.01,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Frieren CC',
    tagline: 'Conquestor Pack #2: Luminous ethereal cyan bloom, glass flare lines, crisp anime outlines',
    category: 'Stylized',
    params: PresetParams(
      brightness: 0.04,
      saturation: 1.20,
      contrast: 1.25,
      sharpness: 0.60,
      gamma: 0.95,
      hue: 0.0,
      temperature: 6600.0,
      glowIntensity: 0.20,
      bloomSpread: 0.38,
      deepGlow: true,
      deepGlowRadius: 0.40,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.30,
      edgeGlowTint: 'cyan',
      anamorphicFlare: 0.03,
      flareAmount: 0.18,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'cyan',
      volumetricLighting: 0.0,
      depthOfField: 0.0,
      lumenRtx: 0.14,
      volumetricFog: 0.06,
      blackCrush: 0.15,
      lookMix: 0.05,
      vignette: 0.10,
      splitToning: 0.06,
      lutIntensity: 0.32,
      darkOutlines: 0.10,
      denoise: 0.0,
      edgeBlur: 0.06,
      grain: 0.015,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Teen Gojo WIS',
    tagline: 'Conquestor Culling Games: Inky black crush, electric purple-cyan deep glow, RTX Lumen bounce',
    category: 'Stylized',
    params: PresetParams(
      brightness: 0.02,
      saturation: 1.22,
      contrast: 1.34,
      sharpness: 0.70,
      gamma: 0.94,
      hue: 0.0,
      temperature: 6700.0,
      glowIntensity: 0.22,
      bloomSpread: 0.44,
      deepGlow: true,
      deepGlowRadius: 0.44,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.32,
      edgeGlowTint: 'electric',
      anamorphicFlare: 0.04,
      flareAmount: 0.20,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'violet',
      volumetricLighting: 0.0,
      depthOfField: 0.0,
      lumenRtx: 0.18,
      volumetricFog: 0.08,
      blackCrush: 0.24,
      lookMix: 0.08,
      vignette: 0.14,
      splitToning: 0.10,
      lutIntensity: 0.38,
      darkOutlines: 0.12,
      denoise: 0.0,
      edgeBlur: 0.08,
      grain: 0.015,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Bleach TYBW Rebirth',
    tagline: 'High-contrast spiritual pressure bloom, dark manga lineart and sharp blade specular highlights',
    category: 'Stylized',
    params: PresetParams(
      brightness: 0.02,
      saturation: 1.18,
      contrast: 1.36,
      sharpness: 0.75,
      gamma: 0.93,
      hue: 0.0,
      temperature: 6500.0,
      glowIntensity: 0.22,
      bloomSpread: 0.42,
      deepGlow: true,
      deepGlowRadius: 0.42,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.30,
      edgeGlowTint: 'white',
      anamorphicFlare: 0.03,
      flareAmount: 0.18,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'white',
      volumetricLighting: 0.0,
      depthOfField: 0.0,
      lumenRtx: 0.16,
      volumetricFog: 0.06,
      blackCrush: 0.26,
      lookMix: 0.06,
      vignette: 0.14,
      splitToning: 0.08,
      lutIntensity: 0.35,
      darkOutlines: 0.14,
      denoise: 0.0,
      edgeBlur: 0.08,
      grain: 0.015,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Bleach Tube',
    tagline: 'Authentic 2000s Bleach CRT Tube & Soul Society atmosphere with subtle warm glow and vintage tape contrast',
    category: 'Vintage',
    params: PresetParams(
      brightness: 0.03,
      saturation: 1.18,
      contrast: 1.30,
      sharpness: 0.65,
      gamma: 0.94,
      hue: 0.0,
      temperature: 6200.0,
      glowIntensity: 0.20,
      bloomSpread: 0.38,
      deepGlow: false,
      deepGlowRadius: 0.30,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.25,
      edgeGlowTint: 'warm',
      anamorphicFlare: 0.0,
      flareAmount: 0.0,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'golden',
      volumetricLighting: 0.0,
      depthOfField: 0.0,
      lumenRtx: 0.12,
      volumetricFog: 0.10,
      blackCrush: 0.22,
      lookMix: 0.10,
      vignette: 0.20,
      splitToning: 0.12,
      lutIntensity: 0.40,
      darkOutlines: 0.10,
      denoise: 0.0,
      edgeBlur: 0.12,
      grain: 0.04,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Jujutsu Cursed Energy',
    tagline: 'Deep inky darks, vibrant indigo-crimson cursed aura glow and intense stylized outline definition',
    category: 'Stylized',
    params: PresetParams(
      brightness: 0.02,
      saturation: 1.25,
      contrast: 1.34,
      sharpness: 0.70,
      gamma: 0.93,
      hue: 0.0,
      temperature: 6600.0,
      glowIntensity: 0.24,
      bloomSpread: 0.44,
      deepGlow: true,
      deepGlowRadius: 0.46,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.32,
      edgeGlowTint: 'crimson',
      anamorphicFlare: 0.03,
      flareAmount: 0.18,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'crimson',
      volumetricLighting: 0.0,
      depthOfField: 0.0,
      lumenRtx: 0.18,
      volumetricFog: 0.10,
      blackCrush: 0.26,
      lookMix: 0.08,
      vignette: 0.16,
      splitToning: 0.10,
      lutIntensity: 0.38,
      darkOutlines: 0.14,
      denoise: 0.0,
      edgeBlur: 0.08,
      grain: 0.02,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Magic Bullet WIS',
    tagline: 'Red Giant Magic Bullet Look: Classic cinematic film print S-curve, Hollywood teal/orange separation, velvety darks and crisp highlight rolloff',
    category: 'Cinematic',
    params: PresetParams(
      brightness: 0.02,
      saturation: 1.18,
      contrast: 1.32,
      sharpness: 0.55,
      gamma: 0.95,
      hue: 0.0,
      temperature: 6100.0,
      glowIntensity: 0.22,
      bloomSpread: 0.40,
      deepGlow: false,
      deepGlowRadius: 0.32,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.30,
      edgeGlowTint: 'warm',
      anamorphicFlare: 0.0,
      flareAmount: 0.0,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'golden',
      volumetricLighting: 0.0,
      depthOfField: 0.0,
      lumenRtx: 0.15,
      volumetricFog: 0.08,
      blackCrush: 0.20,
      lookMix: 0.30,
      vignette: 0.18,
      splitToning: 0.18,
      lutIntensity: 0.45,
      darkOutlines: 0.08,
      denoise: 0.0,
      edgeBlur: 0.06,
      grain: 0.02,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Vintage CC',
    tagline: 'Creepy Liminal Vintage: Eerie desaturated cold tones, heavy shadow falloff, deep vignette, analog halation and film grain',
    category: 'Vintage',
    params: PresetParams(
      brightness: -0.04,
      saturation: 0.72,
      contrast: 1.35,
      sharpness: 0.65,
      gamma: 1.05,
      hue: -6.0,
      temperature: 4900.0,
      glowIntensity: 0.15,
      bloomSpread: 0.35,
      deepGlow: false,
      deepGlowRadius: 0.28,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.25,
      edgeGlowTint: 'white',
      anamorphicFlare: 0.0,
      flareAmount: 0.0,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'golden',
      volumetricLighting: 0.0,
      depthOfField: 0.0,
      lumenRtx: 0.08,
      volumetricFog: 0.25,
      blackCrush: 0.35,
      lookMix: 0.15,
      vignette: 0.42,
      splitToning: 0.35,
      lutIntensity: 0.45,
      darkOutlines: 0.10,
      denoise: 0.0,
      edgeBlur: 0.22,
      grain: 0.08,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Teal & Orange Cine',
    tagline: 'Hollywood blockbuster filmic color matrix with rich shadows and luminous warm skin',
    category: 'Cinematic',
    params: PresetParams(
      brightness: 0.02,
      saturation: 1.18,
      contrast: 1.25,
      sharpness: 0.50,
      gamma: 0.96,
      hue: 0.0,
      temperature: 5900.0,
      glowIntensity: 0.14,
      bloomSpread: 0.35,
      deepGlow: false,
      deepGlowRadius: 0.28,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.0,
      edgeGlowTint: 'warm',
      anamorphicFlare: 0.0,
      flareAmount: 0.0,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'golden',
      volumetricLighting: 0.0,
      depthOfField: 0.0,
      lumenRtx: 0.12,
      volumetricFog: 0.06,
      blackCrush: 0.16,
      lookMix: 0.32,
      vignette: 0.16,
      splitToning: 0.15,
      lutIntensity: 0.40,
      darkOutlines: 0.06,
      denoise: 0.0,
      edgeBlur: 0.05,
      grain: 0.02,
      aspectRatio: '4:5',
    ),
  ),
  PresetLook(
    name: 'Cyberpunk Neon',
    tagline: 'High-voltage ultraviolet & electric cyan with subtle anamorphic flare streaks',
    category: 'Stylized',
    params: PresetParams(
      brightness: 0.04,
      saturation: 1.28,
      contrast: 1.30,
      sharpness: 0.70,
      gamma: 0.93,
      hue: 0.0,
      temperature: 7200.0,
      glowIntensity: 0.26,
      bloomSpread: 0.46,
      deepGlow: true,
      deepGlowRadius: 0.48,
      edgeGlow: 0.0,
      edgeGlowSpread: 0.32,
      edgeGlowTint: 'electric',
      anamorphicFlare: 0.06,
      flareAmount: 0.25,
      godRays: 0.0,
      godRaysDensity: 0.0,
      godRaysColor: 'violet',
      volumetricLighting: 0.0,
      depthOfField: 0.0,
      lumenRtx: 0.20,
      volumetricFog: 0.12,
      blackCrush: 0.20,
      lookMix: 0.16,
      vignette: 0.18,
      splitToning: 0.20,
      lutIntensity: 0.42,
      darkOutlines: 0.12,
      denoise: 0.0,
      edgeBlur: 0.10,
      grain: 0.025,
      aspectRatio: '4:5',
    ),
  ),
];

// Helper to get presets by category
List<PresetLook> getPresetsByCategory(String category) {
  return PRESET_LOOKS.where((p) => p.category == category).toList();
}

// Helper to search presets by name
PresetLook? getPresetByName(String name) {
  try {
    return PRESET_LOOKS.firstWhere((p) => p.name == name);
  } catch (_) {
    return null;
  }
}
